---
#
# Setup/update homebrew junk
#
- hosts: localhost
  vars:
    - gem_cmd: gem
    - git_netrc_src: "/share/git-core/contrib/credential/netrc/git-credential-netrc"
    - git_netrc_dst: "/libexec/git-core/git-credential-netrc"
    - brew_taps:
        - homebrew/dupes
        - homebrew/science
        - homebrew/versions
        - mitchty/yuck
        - mitchty/clang_scan_view
        - mitchty/clang_scan_build
        - mpv-player/mpv
    - brew_with_options:
        tmux:
          options: wrap-pbcopy-and-pbpaste
        emacs:
          options: cocoa,srgb
        curl:
          options: brew_option_options
        python:
          options: universal,framework
        postgres:
          options: no-perl,no-tcl,without-python
    - brew_present:
        - reattach-to-user-namespace
        - gpg
        - git
        - ansible
        - htop
        - youtube-dl
        - ag
        - ispell
        - docbook
        - asciidoc
        - libxml2
        - libxslt
        - readline
        - sqlite
        - gdbm
        - wakeonlan
        - ruby
        - perl
        - lastpass-cli
        - keychain
        - yuck
        - openssl
        - pigz
        - xz
        - pixz
        - pbzip2
        - pv
        - iperf
        - nmap
        - sntop
        - rsync
        - entr
        - iftop
        - tree
        - pngcrush
        - wget
        - mercurial
        - ack
        - ncurses
        - go
        - python3
        - clang-scan-view
        - clang-scan-build
        - gcc
        - llvm
        - neon
        - mpv
        - subversion16
    - brew_head:
        - mobile-shell
    - brew_linked:
        - perl
        - python
    - pips:
        - docutils
        - howdoi
        - pep8
        - pyflakes
        - flake8
    - gems:
        - rubygems-update
        - pry
        - maid
        - gist
    - cpans:
        - File::HomeDir
        - App::cpanminus
        - App::rainbarf
        - Perl::Tidy
        - Perl::Critic
        - Encode
        - Storable
        - List::Util
        - Hash::Util
        - IO::Socket
  # Make shit happen!
  tasks:
    - name: Get brew install location
      shell: >-
        brew config |
        grep HOMEBREW_PREFIX |
        awk -F': ' '{print $2}'
      register: brew_home

    - name: Update Homebrew
      homebrew: update_homebrew=yes

    - name: List outdated homebrews
      command: brew outdated
      register: outdated

    - debug: msg="{{outdated.stdout}}"

    - name: Upgrade Homebrew installs
      homebrew: upgrade_all=yes

    - name: Setup Homebrew taps
      homebrew_tap: name={{item}} state=present
      with_items: brew_taps

    - name: Install state=present with install_options brews
      homebrew: state=present name={{ item.key }} install_options={{ item.value.options }}
      with_dict: brew_with_options

    - name: Install state=present without option brews
      homebrew: state=present name={{ item }}
      with_items: brew_present

    - name: Install state=headhead brews
      homebrew: state=head name={{ item }}
      with_items: brew_head

    # Ok so we need to setup the gpg credential helper for netrc
    - name: Get installed brew git version
      shell: >-
        brew info git 2>&1 |
        head -n 1 |
        awk '{print $3}' |
        sed -e 's/,//g'
      ignore_errors: true
      register: brew_git_version

    - name: Create link for git-credential-netrc to work
      file: >-
        src="{{brew_home.stdout}}/Cellar/git/{{brew_git_version.stdout}}{{git_netrc_src}}"
        dest="{{brew_home.stdout}}/Cellar/git/{{brew_git_version.stdout}}{{git_netrc_dst}}"
        state=link

    # all this because 10.9 doesn't include libxml2 in the platform
    # headers, LAME, also grr
    - name: Get libxml2 pkg path
      shell: >-
        brew --env libxml2 |
        grep PKG_CONFIG_PATH |
        awk -F'=' '{print $2}' |
        sed -e 's/\"//g'
      register: libxml_pkg_config_path

    - name: Get libxml2 pkg libdir
      shell: >-
        brew --env libxml2 |
        grep PKG_CONFIG_LIBDIR |
        awk -F'=' '{print $2}' |
        sed -e 's/\"//g'
      register: libxml_pkg_config_libdir

    - name: Get libxml2 CFLAGS
      environment:
        PKG_CONFIG_PATH: "{{libxml_pkg_config_path.stdout}}"
        PKG_CONFIG_LIBDIR: "{{libxml_pkg_config_libdir.stdout}}"
      command: pkg-config --cflags libxml-2.0
      register: libxml_cflags

    - name: Get libxml2 LIBS
      environment:
        PKG_CONFIG_PATH: "{{libxml_pkg_config_path.stdout}}"
        PKG_CONFIG_LIBDIR: "{{libxml_pkg_config_libdir.stdout}}"
      command: pkg-config --libs libxml-2.0
      register: libxml_libs

    - name: Install Python pip modules
      environment:
        CFLAGS: "{{libxml_cflags.stdout}}"
        LIBS: "{{libxml_libs}}.stdout"
        PKG_CONFIG_PATH: "{{libxml_pkg_config_path.stdout}}"
        PKG_CONFIG_LIBDIR: "{{libxml_pkg_config_libdir.stdout}}"
        XML_CATALOG_FILES: "{{brew_home}}/etc/xml/catalog"
        DYLD_LIBRARY_PATH: "{{brew_home}}/lib"
      command: "{{brew_home.stdout}}/bin/pip install --upgrade {{item}}"
      with_items: pips

    - name: Get full path of homebrew gem
      command: brew --prefix ruby
      register: brew_ruby_dir

    - include: gems.yml gem_cmd="{{brew_ruby_dir.stdout}}/bin/gem" gems=gems gem_cmd=gem

    - name: Get hombrew perl /bin directory
      command: brew --prefix perl
      register: brew_perl_bin

    - name: Install cpanminus
      shell: >-
        curl -kL http://cpanmin.us |
        "{{brew_perl_bin.stdout}}/bin/perl" - App::cpanminus --force --notest

    - name: Install/Update cpan modules
      command: "{{brew_perl_bin.stdout}}/bin/cpanm --notest --force {{item}}"
      with_items: cpans

    - name: Install state=linked brews
      homebrew: state=linked name={{ item }}
      with_items: brew_linked

    - name: brew cleanup
      command: brew cleanup
